In [38]:
import numpy as np

In [39]:
# ---- 1D Numpy Arrays ----
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
for i in list:
    print(i*4)

print(np.mean(list))
print(np.median(list))
print(np.std(list))
print(np.argmax(list))
print(np.argmin(list))
print(np.max(list))
print(np.min(list))

arr = np.array(list)

condition = arr > 20
print(condition)

new_arr = arr[condition]
print(new_arr)

80
108
36
48
124
68
16
200
156
140
24.4
23.5
13.828955130450023
7
6
50
4
[False  True False False  True False False  True  True  True]
[27 31 50 39 35]


In [40]:
# ---- 2D Numpy Arrays ----
matrix = [[5, 12, 17, 9],
          [8, 21, 14, 3],
          [6, 13, 19, 11]]
print(np.shape(matrix))

arr = np.array(matrix)
print(arr[:, 2])
print(arr[1, :])
print(arr*2)

column_mean = np.mean(arr, axis = 0)
print(column_mean)

overall_mean = np.mean(matrix)
print(overall_mean)

find_max = np.max(arr, axis = 0)
print(find_max)
find_min = np.min(arr, axis = 0)
print(find_min)

print(arr.flatten())
# flatten() displayed the nested list in one line horizontally.

flat = arr.flatten()
print(np.argmax(flat))
print(np.argmin(flat))

print(np.unravel_index(np.argmax(flat), arr.shape))
print(np.unravel_index(np.argmin(flat), arr.shape))


boolean_arr = arr[arr > 15]
print(boolean_arr)

sorted_array = np.sort(arr)
print(sorted_array)

(3, 4)
[17 14 19]
[ 8 21 14  3]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
[ 6.33333333 15.33333333 16.66666667  7.66666667]
11.5
[ 8 21 19 11]
[ 5 12 14  3]
[ 5 12 17  9  8 21 14  3  6 13 19 11]
5
7
(np.int64(1), np.int64(1))
(np.int64(1), np.int64(3))
[17 21 19]
[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [41]:
# ---- Prime Star Systems ----
arr = np.array([
    [2, 3, 5],
    [14, 6, 8],
    [11, 13, 17],
    [7, 10, 13]])

def remove_nonprime_rows(array):
    keep_rows = []
    for row in array:
        has_prime = False
        for n in row:
            if n >= 2:
                is_prime = True
                for i in range(2, n // 2 + 1):
                    if n % i == 0:
                        is_prime = False
                if is_prime:
                    has_prime = True
        if has_prime:
            keep_rows += [row]
    return np.array(keep_rows)

print(remove_nonprime_rows(arr))      

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [42]:
# ---- Lets Play Checkers ----
def zero_array():
    arr = np.zeros((8, 8), dtype = 'int')
    for i in range(0, 8, 2):
        arr[i, ::2] = 1
        arr[1::2, 1::2] = 1
    return arr
print(zero_array()) 

def reverse_checkerboard():
    arr = np.zeros((8, 8), dtype = 'int')
    arr[::2, 1::2] = 1 
    arr[1::2, ::2] = 1 
    
    return arr

print(reverse_checkerboard())

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [48]:
# ---- Expanding Universe ----
def expand_str(words, spaces):
    space_str = " " * spaces
    expanded = []
    for word in words:
        new_word = ""
        for letter in word[: -1]:
            new_word += letter + space_str
        new_word += word[-1]
        expanded.append(new_word)
    return np.array(expanded)  
print(expand_str("cluster", 1))

['c' 'l' 'u' 's' 't' 'e' 'r']


In [59]:
# ---- Second Brightest Star ----


def second_brightest(arr):
    sorted_rows = np.sort(arr, axis = 1)[:, ::-1]
    second_value = sorted_rows[:, 1]
    return second_value

np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
print(stars)
print(second_brightest(stars))


[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
[1889 1647 1138 1863 1592]
